spring.application.name=bookStore
server.port = 1001
spring.datasource.name=book
spring.datasource.url = jdbc:mysql://localhost:3306/book?ServerTimezone=UTC
spring.datasource.username = root
spring.datasource.password = root
spring.datasource.driver-class = com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl.auto = update // this is automatically create a table in our database book
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
